###############################################
# LOGIN 4 ROLES
###############################################

### Login HEAD
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "to_truong",
  "password": "totruong@123"
}

### Login DEPUTY
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "pho_chu",
  "password": "phochu@123"
}

### Login ACCOUNTANT
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "ke_toan",
  "password": "ketoan@123"
}

### Login RESIDENT
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "ho_dan",
  "password": "hodan@123"
}


###############################################
# GET RESIDENTS
###############################################

### Get all residents
GET http://localhost:5000/api/residents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkhFQUQiLCJmdWxsbmFtZSI6Ik5ndXnhu4VuIFbEg24gQSIsImlhdCI6MTc2NTE5MTg4NywiZXhwIjoxNzY1Mjc4Mjg3fQ.EvRzorLzpk_6TvmanzC0t8lVLxXtiO31tFbiev7xlg0


###############################################
# GET HOUSEHOLDS
###############################################

### Get all households
GET http://localhost:5000/api/households
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkhFQUQiLCJmdWxsbmFtZSI6Ik5ndXnhu4VuIFbEg24gQSIsImlhdCI6MTc2NTMwOTMyNSwiZXhwIjoxNzY1Mzk1NzI1fQ.gGkLiX94SA8ayh_xiSaAtQI9jBbuwIp0oo7ZNNXzefw
